# Generated by Django 4.2.27 on 2026-01-24 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDisplayConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_order_items', models.BooleanField(default=True)),
                ('show_tax', models.BooleanField(default=True)),
                ('show_promotions', models.BooleanField(default=True)),
                ('idle_message', models.CharField(default='Welcome!', max_length=200)),
                ('idle_image', models.ImageField(blank=True, null=True, upload_to='customer_display/')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('primary_color', models.CharField(default='#4CAF50', max_length=7)),
                ('text_color', models.CharField(default='#333333', max_length=7)),
            ],
            options={
                'db_table': 'pos_customer_display_config',
            },
        ),
        migrations.CreateModel(
            name='CustomerPromotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('display_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], default='image', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Text content or URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('display_duration', models.PositiveIntegerField(default=10, help_text='Duration in seconds')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pos_customer_promotions',
                'ordering': ['display_order'],
            },
        ),
    ]
