# Generated by Django 4.2.27 on 2026-01-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('terminals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdisplayconfig',
            name='terminal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_display', to='terminals.posterminal'),
        ),
    ]
