# Generated by Django 4.2.27 on 2026-01-24 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='floors/')),
                ('background_color', models.CharField(default='#F3F4F6', max_length=7)),
            ],
            options={
                'db_table': 'pos_floors',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('table_number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('seats', models.PositiveIntegerField(default=4)),
                ('min_seats', models.PositiveIntegerField(default=1)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=100)),
                ('height', models.PositiveIntegerField(default=100)),
                ('shape', models.CharField(choices=[('square', 'Square'), ('round', 'Round'), ('rectangle', 'Rectangle'), ('oval', 'Oval')], default='square', max_length=20)),
                ('color', models.CharField(default='#10B981', max_length=7)),
                ('is_occupied', models.BooleanField(default=False)),
                ('appointment_resource_id', models.CharField(blank=True, help_text='External appointment system resource ID', max_length=100)),
            ],
            options={
                'db_table': 'pos_tables',
                'ordering': ['floor', 'table_number'],
            },
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('party_size', models.PositiveIntegerField(default=2)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'pos_table_reservations',
                'ordering': ['reservation_date', 'reservation_time'],
            },
        ),
    ]
