# Generated by Django 4.2.27 on 2026-01-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floors', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='orders.order'),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='floors.table'),
        ),
        migrations.AddField(
            model_name='table',
            name='current_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_table', to='orders.order'),
        ),
        migrations.AddField(
            model_name='table',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='floors.floor'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('floor', 'table_number')},
        ),
    ]
