# Generated by Django 5.0 on 2026-01-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(default="Odoo Cafe", max_length=200),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                ("tax_name", models.CharField(default="GST", max_length=50)),
                ("tax_number", models.CharField(blank=True, max_length=50)),
                ("receipt_header", models.TextField(blank=True)),
                (
                    "receipt_footer",
                    models.TextField(default="Thank you for dining with us!"),
                ),
                ("print_auto", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "pos_system_settings",
            },
        ),
    ]
