# Generated by Django 4.2.27 on 2026-01-24 06:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_customer_display', models.BooleanField(default=True)),
                ('default_kitchen_display', models.BooleanField(default=True)),
                ('receipt_header', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('receipt_printer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('kitchen_printer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cash_drawer_enabled', models.BooleanField(default=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_terminals', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals', to='floors.floor')),
            ],
            options={
                'db_table': 'pos_terminals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('opening_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('opening', 'Opening'), ('open', 'Open'), ('closing', 'Closing'), ('closed', 'Closed')], default='open', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_notes', models.TextField(blank=True)),
                ('closing_notes', models.TextField(blank=True)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sessions', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='terminals.posterminal')),
            ],
            options={
                'db_table': 'pos_sessions',
                'ordering': ['-opening_time'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('in', 'Cash In'), ('out', 'Cash Out')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='terminals.possession')),
            ],
            options={
                'db_table': 'pos_cash_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='possession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('terminal',), name='unique_active_session_per_terminal'),
        ),
    ]
