# Generated by Django 4.2.27 on 2026-01-24 06:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('card_type', models.CharField(blank=True, max_length=20)),
                ('upi_transaction_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'pos_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('credit', 'Store Credit'), ('split', 'Split Payment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or path', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('requires_verification', models.BooleanField(default=False)),
                ('allows_change', models.BooleanField(default=True, help_text='Can give change (cash)')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('terminals', models.ManyToManyField(blank=True, related_name='payment_methods', to='terminals.posterminal')),
            ],
            options={
                'db_table': 'pos_payment_methods',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UPIConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('upi_id', models.CharField(max_length=100)),
                ('merchant_name', models.CharField(max_length=100)),
                ('merchant_code', models.CharField(blank=True, max_length=20)),
                ('qr_box_size', models.PositiveIntegerField(default=10)),
                ('qr_border', models.PositiveIntegerField(default=4)),
                ('auto_verify', models.BooleanField(default=False, help_text='Automatically verify UPI payments (requires integration)')),
                ('verification_timeout', models.PositiveIntegerField(default=300, help_text='Timeout in seconds for payment verification')),
                ('payment_method', models.OneToOneField(limit_choices_to={'method_type': 'upi'}, on_delete=django.db.models.deletion.CASCADE, related_name='upi_config', to='payments.paymentmethod')),
            ],
            options={
                'db_table': 'pos_upi_configurations',
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('order_cancelled', 'Order Cancelled'), ('product_issue', 'Product Issue'), ('wrong_order', 'Wrong Order'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('refund_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pos_payment_refunds',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CardConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_id', models.CharField(blank=True, max_length=50)),
                ('merchant_id', models.CharField(blank=True, max_length=50)),
                ('accept_visa', models.BooleanField(default=True)),
                ('accept_mastercard', models.BooleanField(default=True)),
                ('accept_amex', models.BooleanField(default=True)),
                ('accept_rupay', models.BooleanField(default=True)),
                ('payment_method', models.OneToOneField(limit_choices_to={'method_type': 'card'}, on_delete=django.db.models.deletion.CASCADE, related_name='card_config', to='payments.paymentmethod')),
            ],
            options={
                'db_table': 'pos_card_configurations',
            },
        ),
    ]
