# Generated by Django 4.2.27 on 2026-01-24 06:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminals', '0001_initial'),
        ('products', '0001_initial'),
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfOrderCart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'pos_self_order_carts',
            },
        ),
        migrations.CreateModel(
            name='SelfOrderCartItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='self_order.selfordercart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
            options={
                'db_table': 'pos_self_order_cart_items',
            },
        ),
        migrations.CreateModel(
            name='SelfOrderSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('table_qr', 'Table QR Code'), ('takeaway_qr', 'Takeaway QR Code'), ('kiosk', 'Kiosk')], max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('pos_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_order_sessions', to='terminals.possession')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_order_sessions', to='floors.table')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_order_sessions', to='terminals.posterminal')),
            ],
            options={
                'db_table': 'pos_self_order_sessions',
            },
        ),
        migrations.CreateModel(
            name='SelfOrderQRCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='floors.table')),
            ],
            options={
                'db_table': 'pos_self_order_qr_codes',
            },
        ),
        migrations.CreateModel(
            name='SelfOrderCartItemModifier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='self_order.selfordercartitem')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodifier')),
            ],
            options={
                'db_table': 'pos_self_order_cart_item_modifiers',
            },
        ),
        migrations.AddField(
            model_name='selfordercart',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='self_order.selfordersession'),
        ),
    ]
